#!/bin/bash

green='\033[0;32m'
yellow='\033[0;33m'
red='\033[0;31m'
bold=`tput bold`
normal=`tput sgr0`
end_color='\033[0;m'

FORCE=${FORCE:-0}

if [ -d "$HOME/.vim" ]; then
  if [ $FORCE == 1 ]; then
    echo -e "${yellow}${bold}WARN${end_color}: Moving existing vim config to $HOME/.vim.old"
    mv $HOME/.vim $HOME/.vim.old
  else
    echo -e "${red}${bold}ERROR${end_color}: Found existing vim config. Aborting. Run with FORCE=1 to override"
    exit 1
  fi
fi

git clone http://github.com/luan/vimfiles.git $HOME/.vim
$HOME/.vim/install
